/* Copyright (C) 2018. Hitomi Parser Developers */

namespace Hitomi_Copy_3
{
    public static class KoreanTag
    {
        public static string TagMap(string eng_tag)
        {
            switch (eng_tag)
            {
                case "group": return "그룹";
                case "mosaic censorship": return "모자이크 검열";
                case "incest": return "근친";
                case "full color": return "풀컬러";
                case "tankoubon": return "단행본";
                case "ffm threesome": return "여여남 쓰리썸";
                case "full censorship": return "완전 검열";
                case "mmf threesome": return "남남여 쓰리썸";
                case "story arc": return "스토리 아크";
                case "uncensored": return "미검열";
                case "multi-work series": return "multi-work series";
                case "anthology": return "시집";
                case "replaced": return "replaced";
                case "webtoon": return "웹툰";
                case "incomplete": return "미완성";
                case "inseki": return "inseki";
                case "scanmark": return "스캔 마크";
                case "sample": return "샘플";
                case "rewrite": return "rewrite";
                case "novel": return "소설";
                case "animated": return "애니";
                case "artbook": return "아트북";
                case "body swap": return "body swap";
                case "out of order": return "out of order";
                case "time stop": return "time stop";
                case "missing cover": return "missing cover";
                case "monster": return "monster";
                case "mtf threesome": return "mtf threesome";
                case "3d": return "3d";
                case "twins": return "twins";
                case "ttm threesome": return "ttm threesome";
                case "compilation": return "compilation";
                case "oyakodon": return "oyakodon";
                case "poor grammar": return "poor grammar";
                case "watermarked": return "watermarked";
                case "game sprite": return "game sprite";
                case "mmt threesome": return "mmt threesome";
                case "miyamoto smoke": return "miyamoto smoke";
                case "variant set": return "variant set";
                case "tuna empire": return "tuna empire";
                case "nudity only": return "nudity only";
                case "comedy": return "comedy";
                case "levi": return "levi";
                case "frottage": return "frottage";
                case "meganekko": return "meganekko";
                case "husky guy": return "husky guy";
                case "roman shoten": return "roman shoten";
                case "shinozuka jouji": return "shinozuka jouji";
                case "animal on animal": return "animal on animal";
                case "redraw": return "redraw";
                case "chiyou yoyuchi": return "chiyou yoyuchi";
                case "takuji": return "takuji";
                case "horror": return "horror";
                case "manga": return "manga";
                case "female:big breasts": return "female:big breasts";
                case "female:loli": return "female:loli";
                case "female:stockings": return "female:stockings";
                case "female:schoolgirl uniform": return "female:schoolgirl uniform";
                case "female:sole female": return "female:sole female";
                case "female:anal": return "female:anal";
                case "female:nakadashi": return "female:nakadashi";
                case "female:bondage": return "female:bondage";
                case "female:blowjob": return "female:blowjob";
                case "female:rape": return "female:rape";
                case "female:glasses": return "female:glasses";
                case "female:ahegao": return "female:ahegao";
                case "female:paizuri": return "female:paizuri";
                case "female:defloration": return "female:defloration";
                case "female:double penetration": return "female:double penetration";
                case "female:milf": return "female:milf";
                case "female:sex toys": return "female:sex toys";
                case "female:futanari": return "female:futanari";
                case "female:x-ray": return "female:x-ray";
                case "female:swimsuit": return "female:swimsuit";
                case "female:yuri": return "female:yuri";
                case "female:femdom": return "female:femdom";
                case "female:tentacles": return "female:tentacles";
                case "female:impregnation": return "female:impregnation";
                case "female:sister": return "female:sister";
                case "female:netorare": return "female:netorare";
                case "female:pregnant": return "female:pregnant";
                case "female:pantyhose": return "female:pantyhose";
                case "female:mind break": return "female:mind break";
                case "female:lactation": return "female:lactation";
                case "female:dark skin": return "female:dark skin";
                case "female:collar": return "female:collar";
                case "female:footjob": return "female:footjob";
                case "female:maid": return "female:maid";
                case "female:big ass": return "female:big ass";
                case "female:bikini": return "female:bikini";
                case "female:cheating": return "female:cheating";
                case "female:urination": return "female:urination";
                case "female:mother": return "female:mother";
                case "female:catgirl": return "female:catgirl";
                case "female:gag": return "female:gag";
                case "female:masturbation": return "female:masturbation";
                case "female:handjob": return "female:handjob";
                case "female:exhibitionism": return "female:exhibitionism";
                case "female:garter belt": return "female:garter belt";
                case "female:mind control": return "female:mind control";
                case "female:huge breasts": return "female:huge breasts";
                case "female:bloomers": return "female:bloomers";
                case "female:small breasts": return "female:small breasts";
                case "female:bukkake": return "female:bukkake";
                case "female:scat": return "female:scat";
                case "female:females only": return "female:females only";
                case "female:hairy": return "female:hairy";
                case "female:harem": return "female:harem";
                case "female:blindfold": return "female:blindfold";
                case "female:inflation": return "female:inflation";
                case "female:teacher": return "female:teacher";
                case "female:lingerie": return "female:lingerie";
                case "female:demon girl": return "female:demon girl";
                case "female:piercing": return "female:piercing";
                case "female:bbw": return "female:bbw";
                case "female:bunny girl": return "female:bunny girl";
                case "female:elf": return "female:elf";
                case "female:tanlines": return "female:tanlines";
                case "female:drugs": return "female:drugs";
                case "female:kimono": return "female:kimono";
                case "female:bestiality": return "female:bestiality";
                case "female:fingering": return "female:fingering";
                case "female:stomach deformation": return "female:stomach deformation";
                case "female:prostitution": return "female:prostitution";
                case "female:school swimsuit": return "female:school swimsuit";
                case "female:cunnilingus": return "female:cunnilingus";
                case "female:enema": return "female:enema";
                case "female:unusual pupils": return "female:unusual pupils";
                case "female:nurse": return "female:nurse";
                case "female:strap-on": return "female:strap-on";
                case "female:monster girl": return "female:monster girl";
                case "female:sweating": return "female:sweating";
                case "female:birth": return "female:birth";
                case "female:sleeping": return "female:sleeping";
                case "female:spanking": return "female:spanking";
                case "female:rimjob": return "female:rimjob";
                case "female:miko": return "female:miko";
                case "female:apron": return "female:apron";
                case "female:blackmail": return "female:blackmail";
                case "female:deepthroat": return "female:deepthroat";
                case "female:kissing": return "female:kissing";
                case "female:daughter": return "female:daughter";
                case "female:bodysuit": return "female:bodysuit";
                case "female:big penis": return "female:big penis";
                case "female:schoolgirl": return "female:schoolgirl";
                case "female:shibari": return "female:shibari";
                case "female:thigh high boots": return "female:thigh high boots";
                case "female:breast expansion": return "female:breast expansion";
                case "female:furry": return "female:furry";
                case "female:gyaru": return "female:gyaru";
                case "female:dick growth": return "female:dick growth";
                case "female:slave": return "female:slave";
                case "female:latex": return "female:latex";
                case "female:leotard": return "female:leotard";
                case "female:big areolae": return "female:big areolae";
                case "female:filming": return "female:filming";
                case "female:magical girl": return "female:magical girl";
                case "female:cervix penetration": return "female:cervix penetration";
                case "female:guro": return "female:guro";
                case "female:corruption": return "female:corruption";
                case "female:hairy armpits": return "female:hairy armpits";
                case "female:nipple fuck": return "female:nipple fuck";
                case "female:chloroform": return "female:chloroform";
                case "female:bike shorts": return "female:bike shorts";
                case "female:fisting": return "female:fisting";
                case "female:urethra insertion": return "female:urethra insertion";
                case "female:dickgirl on dickgirl": return "female:dickgirl on dickgirl";
                case "female:tiara": return "female:tiara";
                case "female:fox girl": return "female:fox girl";
                case "female:inverted nipples": return "female:inverted nipples";
                case "female:bdsm": return "female:bdsm";
                case "female:group": return "female:group";
                case "female:crossdressing": return "female:crossdressing";
                case "female:shemale": return "female:shemale";
                case "female:human pet": return "female:human pet";
                case "female:incest": return "female:incest";
                case "female:chikan": return "female:chikan";
                case "female:tomboy": return "female:tomboy";
                case "female:big nipples": return "female:big nipples";
                case "female:torture": return "female:torture";
                case "female:facesitting": return "female:facesitting";
                case "female:leg lock": return "female:leg lock";
                case "female:gokkun": return "female:gokkun";
                case "female:sole dickgirl": return "female:sole dickgirl";
                case "female:waitress": return "female:waitress";
                case "female:oppai loli": return "female:oppai loli";
                case "female:muscle": return "female:muscle";
                case "female:male on dickgirl": return "female:male on dickgirl";
                case "female:large insertions": return "female:large insertions";
                case "female:tribadism": return "female:tribadism";
                case "female:eggs": return "female:eggs";
                case "female:body writing": return "female:body writing";
                case "female:business suit": return "female:business suit";
                case "female:eyepatch": return "female:eyepatch";
                case "female:shimapan": return "female:shimapan";
                case "female:nun": return "female:nun";
                case "female:hotpants": return "female:hotpants";
                case "female:ryona": return "female:ryona";
                case "female:bride": return "female:bride";
                case "female:drunk": return "female:drunk";
                case "female:wings": return "female:wings";
                case "female:transformation": return "female:transformation";
                case "female:squirting": return "female:squirting";
                case "female:humiliation": return "female:humiliation";
                case "female:cousin": return "female:cousin";
                case "female:snuff": return "female:snuff";
                case "female:double vaginal": return "female:double vaginal";
                case "female:tall girl": return "female:tall girl";
                case "female:armpit sex": return "female:armpit sex";
                case "female:triple penetration": return "female:triple penetration";
                case "female:dog girl": return "female:dog girl";
                case "female:breast feeding": return "female:breast feeding";
                case "female:blowjob face": return "female:blowjob face";
                case "female:vore": return "female:vore";
                case "female:cheerleader": return "female:cheerleader";
                case "female:smell": return "female:smell";
                case "female:milking": return "female:milking";
                case "female:slime": return "female:slime";
                case "female:gaping": return "female:gaping";
                case "female:body modification": return "female:body modification";
                case "female:cosplaying": return "female:cosplaying";
                case "female:robot": return "female:robot";
                case "female:sundress": return "female:sundress";
                case "female:angel": return "female:angel";
                case "female:prolapse": return "female:prolapse";
                case "female:underwater": return "female:underwater";
                case "female:twins": return "female:twins";
                case "female:yandere": return "female:yandere";
                case "female:amputee": return "female:amputee";
                case "female:military": return "female:military";
                case "female:kunoichi": return "female:kunoichi";
                case "female:metal armor": return "female:metal armor";
                case "female:nose hook": return "female:nose hook";
                case "female:aunt": return "female:aunt";
                case "female:giantess": return "female:giantess";
                case "female:big clit": return "female:big clit";
                case "female:possession": return "female:possession";
                case "female:corset": return "female:corset";
                case "female:diaper": return "female:diaper";
                case "female:chinese dress": return "female:chinese dress";
                case "female:bisexual": return "female:bisexual";
                case "female:piss drinking": return "female:piss drinking";
                case "female:public use": return "female:public use";
                case "female:machine": return "female:machine";
                case "female:oni": return "female:oni";
                case "female:parasite": return "female:parasite";
                case "female:cowgirl": return "female:cowgirl";
                case "female:all the way through": return "female:all the way through";
                case "female:witch": return "female:witch";
                case "female:hairjob": return "female:hairjob";
                case "female:kemonomimi": return "female:kemonomimi";
                case "female:sumata": return "female:sumata";
                case "female:blood": return "female:blood";
                case "female:wolf girl": return "female:wolf girl";
                case "female:solo action": return "female:solo action";
                case "female:crotch tattoo": return "female:crotch tattoo";
                case "female:lab coat": return "female:lab coat";
                case "female:tracksuit": return "female:tracksuit";
                case "female:christmas": return "female:christmas";
                case "female:insect": return "female:insect";
                case "female:age progression": return "female:age progression";
                case "female:farting": return "female:farting";
                case "female:policewoman": return "female:policewoman";
                case "female:oyakodon": return "female:oyakodon";
                case "female:tail plug": return "female:tail plug";
                case "female:vomit": return "female:vomit";
                case "female:gothic lolita": return "female:gothic lolita";
                case "female:mecha girl": return "female:mecha girl";
                case "female:vampire": return "female:vampire";
                case "female:double anal": return "female:double anal";
                case "female:pasties": return "female:pasties";
                case "female:low lolicon": return "female:low lolicon";
                case "female:gender bender": return "female:gender bender";
                case "female:randoseru": return "female:randoseru";
                case "female:assjob": return "female:assjob";
                case "female:emotionless sex": return "female:emotionless sex";
                case "female:toddlercon": return "female:toddlercon";
                case "female:asphyxiation": return "female:asphyxiation";
                case "female:dougi": return "female:dougi";
                case "female:armpit licking": return "female:armpit licking";
                case "female:stuck in wall": return "female:stuck in wall";
                case "female:dark nipples": return "female:dark nipples";
                case "female:full body tattoo": return "female:full body tattoo";
                case "female:multiple paizuri": return "female:multiple paizuri";
                case "female:tickling": return "female:tickling";
                case "female:fairy": return "female:fairy";
                case "female:moral degeneration": return "female:moral degeneration";
                case "female:beauty mark": return "female:beauty mark";
                case "female:chastity belt": return "female:chastity belt";
                case "female:big balls": return "female:big balls";
                case "female:pillory": return "female:pillory";
                case "female:eyemask": return "female:eyemask";
                case "female:huge penis": return "female:huge penis";
                case "female:orgasm denial": return "female:orgasm denial";
                case "female:minigirl": return "female:minigirl";
                case "female:swinging": return "female:swinging";
                case "female:coprophagia": return "female:coprophagia";
                case "female:widow": return "female:widow";
                case "female:snake girl": return "female:snake girl";
                case "female:ghost": return "female:ghost";
                case "female:wooden horse": return "female:wooden horse";
                case "female:tube": return "female:tube";
                case "female:electric shocks": return "female:electric shocks";
                case "female:niece": return "female:niece";
                case "female:masked face": return "female:masked face";
                case "female:selfcest": return "female:selfcest";
                case "female:ball sucking": return "female:ball sucking";
                case "female:age regression": return "female:age regression";
                case "female:brain fuck": return "female:brain fuck";
                case "female:ponytail": return "female:ponytail";
                case "female:long tongue": return "female:long tongue";
                case "female:autofellatio": return "female:autofellatio";
                case "female:wrestling": return "female:wrestling";
                case "female:foot licking": return "female:foot licking";
                case "female:twintails": return "female:twintails";
                case "female:speculum": return "female:speculum";
                case "female:freckles": return "female:freckles";
                case "female:living clothes": return "female:living clothes";
                case "female:bandages": return "female:bandages";
                case "female:unbirth": return "female:unbirth";
                case "female:slime girl": return "female:slime girl";
                case "female:double blowjob": return "female:double blowjob";
                case "female:voyeurism": return "female:voyeurism";
                case "female:pubic stubble": return "female:pubic stubble";
                case "female:ttf threesome": return "female:ttf threesome";
                case "female:pantyjob": return "female:pantyjob";
                case "female:human cattle": return "female:human cattle";
                case "female:mermaid": return "female:mermaid";
                case "female:clit growth": return "female:clit growth";
                case "female:whip": return "female:whip";
                case "female:condom": return "female:condom";
                case "female:scar": return "female:scar";
                case "female:zombie": return "female:zombie";
                case "female:fundoshi": return "female:fundoshi";
                case "female:onahole": return "female:onahole";
                case "female:clothed paizuri": return "female:clothed paizuri";
                case "female:multiple penises": return "female:multiple penises";
                case "female:catfight": return "female:catfight";
                case "female:tutor": return "female:tutor";
                case "female:tights": return "female:tights";
                case "female:smegma": return "female:smegma";
                case "female:lizard girl": return "female:lizard girl";
                case "female:centaur": return "female:centaur";
                case "female:body painting": return "female:body painting";
                case "female:petrification": return "female:petrification";
                case "female:multiple breasts": return "female:multiple breasts";
                case "female:crown": return "female:crown";
                case "female:low bestiality": return "female:low bestiality";
                case "female:glory hole": return "female:glory hole";
                case "female:gymshorts": return "female:gymshorts";
                case "female:dicknipples": return "female:dicknipples";
                case "female:harpy": return "female:harpy";
                case "female:skinsuit": return "female:skinsuit";
                case "female:sunglasses": return "female:sunglasses";
                case "female:smoking": return "female:smoking";
                case "female:cum swap": return "female:cum swap";
                case "female:bodystocking": return "female:bodystocking";
                case "female:insect girl": return "female:insect girl";
                case "female:oil": return "female:oil";
                case "female:vaginal sticker": return "female:vaginal sticker";
                case "female:frottage": return "female:frottage";
                case "female:nipple expansion": return "female:nipple expansion";
                case "female:cbt": return "female:cbt";
                case "female:wormhole": return "female:wormhole";
                case "female:phimosis": return "female:phimosis";
                case "female:squid girl": return "female:squid girl";
                case "female:plant girl": return "female:plant girl";
                case "female:weight gain": return "female:weight gain";
                case "female:dickgirls only": return "female:dickgirls only";
                case "female:mouse girl": return "female:mouse girl";
                case "female:gigantic breasts": return "female:gigantic breasts";
                case "female:heterochromia": return "female:heterochromia";
                case "female:table masturbation": return "female:table masturbation";
                case "female:horse girl": return "female:horse girl";
                case "female:dark sclera": return "female:dark sclera";
                case "female:forniphilia": return "female:forniphilia";
                case "female:schoolboy uniform": return "female:schoolboy uniform";
                case "female:syringe": return "female:syringe";
                case "female:mature": return "female:mature";
                case "female:spider girl": return "female:spider girl";
                case "female:human on furry": return "female:human on furry";
                case "female:snake": return "female:snake";
                case "female:navel fuck": return "female:navel fuck";
                case "female:fft threesome": return "female:fft threesome";
                case "female:alien girl": return "female:alien girl";
                case "female:stewardess": return "female:stewardess";
                case "female:raccoon girl": return "female:raccoon girl";
                case "female:ear fuck": return "female:ear fuck";
                case "female:octopus": return "female:octopus";
                case "female:worm": return "female:worm";
                case "female:doll joints": return "female:doll joints";
                case "female:sheep girl": return "female:sheep girl";
                case "female:wet clothes": return "female:wet clothes";
                case "female:shared senses": return "female:shared senses";
                case "female:growth": return "female:growth";
                case "female:absorption": return "female:absorption";
                case "female:cashier": return "female:cashier";
                case "female:big vagina": return "female:big vagina";
                case "female:infantilism": return "female:infantilism";
                case "female:invisible": return "female:invisible";
                case "female:stretching": return "female:stretching";
                case "female:saliva": return "female:saliva";
                case "female:handicapped": return "female:handicapped";
                case "female:cum bath": return "female:cum bath";
                case "female:unusual teeth": return "female:unusual teeth";
                case "female:coach": return "female:coach";
                case "female:autopaizuri": return "female:autopaizuri";
                case "female:girls only": return "female:girls only";
                case "female:necrophilia": return "female:necrophilia";
                case "female:anorexic": return "female:anorexic";
                case "female:pig girl": return "female:pig girl";
                case "female:menstruation": return "female:menstruation";
                case "female:anal birth": return "female:anal birth";
                case "female:tailjob": return "female:tailjob";
                case "female:cannibalism": return "female:cannibalism";
                case "female:pirate": return "female:pirate";
                case "female:male on futanari": return "female:male on futanari";
                case "female:triple vaginal": return "female:triple vaginal";
                case "female:eel": return "female:eel";
                case "female:granddaughter": return "female:granddaughter";
                case "female:slug": return "female:slug";
                case "female:futanari on futanari": return "female:futanari on futanari";
                case "female:prostate massage": return "female:prostate massage";
                case "female:ass expansion": return "female:ass expansion";
                case "female:body swap": return "female:body swap";
                case "female:nipple birth": return "female:nipple birth";
                case "female:pole dancing": return "female:pole dancing";
                case "female:race queen": return "female:race queen";
                case "female:blind": return "female:blind";
                case "female:dragon": return "female:dragon";
                case "female:big lips": return "female:big lips";
                case "female:frog": return "female:frog";
                case "female:eye penetration": return "female:eye penetration";
                case "female:kigurumi": return "female:kigurumi";
                case "female:shrinking": return "female:shrinking";
                case "female:nose fuck": return "female:nose fuck";
                case "female:orc": return "female:orc";
                case "female:triple anal": return "female:triple anal";
                case "female:multiple arms": return "female:multiple arms";
                case "female:prehensile hair": return "female:prehensile hair";
                case "female:inseki": return "female:inseki";
                case "female:ponygirl": return "female:ponygirl";
                case "female:grandmother": return "female:grandmother";
                case "female:midget": return "female:midget";
                case "female:foot insertion": return "female:foot insertion";
                case "female:layer cake": return "female:layer cake";
                case "female:cum in eye": return "female:cum in eye";
                case "female:bandaid": return "female:bandaid";
                case "female:phone sex": return "female:phone sex";
                case "female:horse": return "female:horse";
                case "female:balls expansion": return "female:balls expansion";
                case "female:spider": return "female:spider";
                case "female:bee girl": return "female:bee girl";
                case "female:vacbed": return "female:vacbed";
                case "female:balljob": return "female:balljob";
                case "female:clamp": return "female:clamp";
                case "female:kneepit sex": return "female:kneepit sex";
                case "female:squirrel girl": return "female:squirrel girl";
                case "female:gasmask": return "female:gasmask";
                case "female:monoeye": return "female:monoeye";
                case "female:kindergarten uniform": return "female:kindergarten uniform";
                case "female:abortion": return "female:abortion";
                case "female:trampling": return "female:trampling";
                case "female:old lady": return "female:old lady";
                case "female:sockjob": return "female:sockjob";
                case "female:maggot": return "female:maggot";
                case "female:ssbbw": return "female:ssbbw";
                case "female:kappa": return "female:kappa";
                case "female:albino": return "female:albino";
                case "female:nazi": return "female:nazi";
                case "female:frog girl": return "female:frog girl";
                case "female:horse cock": return "female:horse cock";
                case "female:monkey": return "female:monkey";
                case "female:robot girl": return "female:robot girl";
                case "female:scrotal lingerie": return "female:scrotal lingerie";
                case "female:first person perspective": return "female:first person perspective";
                case "female:bald": return "female:bald";
                case "female:hijab": return "female:hijab";
                case "female:dog": return "female:dog";
                case "female:legjob": return "female:legjob";
                case "female:breast reduction": return "female:breast reduction";
                case "female:cow": return "female:cow";
                case "female:tooth brushing": return "female:tooth brushing";
                case "female:rabbit": return "female:rabbit";
                case "female:burping": return "female:burping";
                case "female:penis birth": return "female:penis birth";
                case "female:haigure": return "female:haigure";
                case "female:cat": return "female:cat";
                case "female:fox": return "female:fox";
                case "female:forced": return "female:forced";
                case "female:mute": return "female:mute";
                case "female:harness": return "female:harness";
                case "female:butler": return "female:butler";
                case "female:fish": return "female:fish";
                case "female:pig": return "female:pig";
                case "female:snail girl": return "female:snail girl";
                case "female:goblin": return "female:goblin";
                case "female:multiple nipples": return "female:multiple nipples";
                case "female:piercings": return "female:piercings";
                case "female:muscle growth": return "female:muscle growth";
                case "female:cockslapping": return "female:cockslapping";
                case "female:tiger": return "female:tiger";
                case "female:donkey": return "female:donkey";
                case "female:panda girl": return "female:panda girl";
                case "female:mouse": return "female:mouse";
                case "female:adventitious vagina": return "female:adventitious vagina";
                case "female:reptile": return "female:reptile";
                case "female:shark girl": return "female:shark girl";
                case "female:conjoined": return "female:conjoined";
                case "female:dismantling": return "female:dismantling";
                case "female:lioness": return "female:lioness";
                case "female:schoolboy": return "female:schoolboy";
                case "female:dolphin": return "female:dolphin";
                case "female:wolf": return "female:wolf";
                case "female:bear girl": return "female:bear girl";
                case "female:elephant": return "female:elephant";
                case "female:animal on furry": return "female:animal on furry";
                case "female:gijinka": return "female:gijinka";
                case "female:multiple vaginas": return "female:multiple vaginas";
                case "female:bear": return "female:bear";
                case "female:draenei": return "female:draenei";
                case "female:sheep": return "female:sheep";
                case "female:closed eyes": return "female:closed eyes";
                case "female:kangaroo": return "female:kangaroo";
                case "female:unicorn": return "female:unicorn";
                case "female:dinosaur": return "female:dinosaur";
                case "female:waiter": return "female:waiter";
                case "female:school uniform": return "female:school uniform";
                case "female:blow job": return "female:blow job";
                case "female:gymshort": return "female:gymshort";
                case "female:futa": return "female:futa";
                case "female:clown": return "female:clown";
                case "female:demon": return "female:demon";
                case "female:amputation": return "female:amputation";
                case "female:nose hooks": return "female:nose hooks";
                case "female:spats": return "female:spats";
                case "female:ogre": return "female:ogre";
                case "female:dragonfly": return "female:dragonfly";
                case "female:stocking": return "female:stocking";
                case "female:tail": return "female:tail";
                case "female:tall": return "female:tall";
                case "female:tattoo": return "female:tattoo";
                case "female:throat bulging": return "female:throat bulging";
                case "female:maids": return "female:maids";
                case "female:braces": return "female:braces";
                case "female:crab": return "female:crab";
                case "female:irrumatio": return "female:irrumatio";
                case "female:insects": return "female:insects";
                case "female:bandage": return "female:bandage";
                case "female:shrink": return "female:shrink";
                case "female:larva": return "female:larva";
                case "female:lamia": return "female:lamia";
                case "female:kneesock": return "female:kneesock";
                case "female:worms": return "female:worms";
                case "female:leeches": return "female:leeches";
                case "female:animal on animal": return "female:animal on animal";
                case "female:bf": return "female:bf";
                case "female:snails": return "female:snails";
                case "male:sole male": return "male:sole male";
                case "male:shota": return "male:shota";
                case "male:yaoi": return "male:yaoi";
                case "male:anal": return "male:anal";
                case "male:glasses": return "male:glasses";
                case "male:males only": return "male:males only";
                case "male:dilf": return "male:dilf";
                case "male:schoolboy uniform": return "male:schoolboy uniform";
                case "male:crossdressing": return "male:crossdressing";
                case "male:bbm": return "male:bbm";
                case "male:dark skin": return "male:dark skin";
                case "male:tomgirl": return "male:tomgirl";
                case "male:muscle": return "male:muscle";
                case "male:gender bender": return "male:gender bender";
                case "male:bondage": return "male:bondage";
                case "male:big penis": return "male:big penis";
                case "male:monster": return "male:monster";
                case "male:condom": return "male:condom";
                case "male:teacher": return "male:teacher";
                case "male:virginity": return "male:virginity";
                case "male:furry": return "male:furry";
                case "male:blowjob": return "male:blowjob";
                case "male:stockings": return "male:stockings";
                case "male:military": return "male:military";
                case "male:rape": return "male:rape";
                case "male:group": return "male:group";
                case "male:harem": return "male:harem";
                case "male:old man": return "male:old man";
                case "male:pegging": return "male:pegging";
                case "male:sex toys": return "male:sex toys";
                case "male:cheating": return "male:cheating";
                case "male:dickgirl on male": return "male:dickgirl on male";
                case "male:dog": return "male:dog";
                case "male:prostate massage": return "male:prostate massage";
                case "male:ahegao": return "male:ahegao";
                case "male:schoolgirl uniform": return "male:schoolgirl uniform";
                case "male:masturbation": return "male:masturbation";
                case "male:nakadashi": return "male:nakadashi";
                case "male:business suit": return "male:business suit";
                case "male:kimono": return "male:kimono";
                case "male:collar": return "male:collar";
                case "male:masked face": return "male:masked face";
                case "male:demon": return "male:demon";
                case "male:blindfold": return "male:blindfold";
                case "male:snuff": return "male:snuff";
                case "male:orc": return "male:orc";
                case "male:cbt": return "male:cbt";
                case "male:catboy": return "male:catboy";
                case "male:foot licking": return "male:foot licking";
                case "male:exhibitionism": return "male:exhibitionism";
                case "male:handjob": return "male:handjob";
                case "male:incest": return "male:incest";
                case "male:swimsuit": return "male:swimsuit";
                case "male:feminization": return "male:feminization";
                case "male:blood": return "male:blood";
                case "male:bald": return "male:bald";
                case "male:rimjob": return "male:rimjob";
                case "male:urethra insertion": return "male:urethra insertion";
                case "male:mind break": return "male:mind break";
                case "male:smegma": return "male:smegma";
                case "male:drugs": return "male:drugs";
                case "male:tentacles": return "male:tentacles";
                case "male:urination": return "male:urination";
                case "male:orgasm denial": return "male:orgasm denial";
                case "male:tracksuit": return "male:tracksuit";
                case "male:sweating": return "male:sweating";
                case "male:maid": return "male:maid";
                case "male:brother": return "male:brother";
                case "male:human on furry": return "male:human on furry";
                case "male:gag": return "male:gag";
                case "male:netorare": return "male:netorare";
                case "male:sunglasses": return "male:sunglasses";
                case "male:horse": return "male:horse";
                case "male:lingerie": return "male:lingerie";
                case "male:tall man": return "male:tall man";
                case "male:tanlines": return "male:tanlines";
                case "male:sleeping": return "male:sleeping";
                case "male:frottage": return "male:frottage";
                case "male:guro": return "male:guro";
                case "male:schoolboy": return "male:schoolboy";
                case "male:pig": return "male:pig";
                case "male:mind control": return "male:mind control";
                case "male:voyeurism": return "male:voyeurism";
                case "male:onahole": return "male:onahole";
                case "male:coach": return "male:coach";
                case "male:prostitution": return "male:prostitution";
                case "male:scar": return "male:scar";
                case "male:elf": return "male:elf";
                case "male:kissing": return "male:kissing";
                case "male:chastity belt": return "male:chastity belt";
                case "male:blackmail": return "male:blackmail";
                case "male:josou seme": return "male:josou seme";
                case "male:piss drinking": return "male:piss drinking";
                case "male:miniguy": return "male:miniguy";
                case "male:lab coat": return "male:lab coat";
                case "male:unusual pupils": return "male:unusual pupils";
                case "male:bunny boy": return "male:bunny boy";
                case "male:x-ray": return "male:x-ray";
                case "male:ryona": return "male:ryona";
                case "male:huge penis": return "male:huge penis";
                case "male:humiliation": return "male:humiliation";
                case "male:footjob": return "male:footjob";
                case "male:pantyhose": return "male:pantyhose";
                case "male:wolf boy": return "male:wolf boy";
                case "male:bdsm": return "male:bdsm";
                case "male:dog boy": return "male:dog boy";
                case "male:bikini": return "male:bikini";
                case "male:eyepatch": return "male:eyepatch";
                case "male:transformation": return "male:transformation";
                case "male:spanking": return "male:spanking";
                case "male:eyemask": return "male:eyemask";
                case "male:scat": return "male:scat";
                case "male:double anal": return "male:double anal";
                case "male:guys only": return "male:guys only";
                case "male:pig man": return "male:pig man";
                case "male:drunk": return "male:drunk";
                case "male:invisible": return "male:invisible";
                case "male:double penetration": return "male:double penetration";
                case "male:torture": return "male:torture";
                case "male:bisexual": return "male:bisexual";
                case "male:hairy": return "male:hairy";
                case "male:smell": return "male:smell";
                case "male:slave": return "male:slave";
                case "male:tutor": return "male:tutor";
                case "male:garter belt": return "male:garter belt";
                case "male:zombie": return "male:zombie";
                case "male:gyaru-oh": return "male:gyaru-oh";
                case "male:piercing": return "male:piercing";
                case "male:cosplaying": return "male:cosplaying";
                case "male:bestiality": return "male:bestiality";
                case "male:first person perspective": return "male:first person perspective";
                case "male:phimosis": return "male:phimosis";
                case "male:fox boy": return "male:fox boy";
                case "male:school swimsuit": return "male:school swimsuit";
                case "male:goblin": return "male:goblin";
                case "male:vore": return "male:vore";
                case "male:bandages": return "male:bandages";
                case "male:inflation": return "male:inflation";
                case "male:age regression": return "male:age regression";
                case "male:dougi": return "male:dougi";
                case "male:oni": return "male:oni";
                case "male:bodysuit": return "male:bodysuit";
                case "male:chikan": return "male:chikan";
                case "male:father": return "male:father";
                case "male:dragon": return "male:dragon";
                case "male:shibari": return "male:shibari";
                case "male:possession": return "male:possession";
                case "male:robot": return "male:robot";
                case "male:bukkake": return "male:bukkake";
                case "male:twins": return "male:twins";
                case "male:unbirth": return "male:unbirth";
                case "male:filming": return "male:filming";
                case "male:minotaur": return "male:minotaur";
                case "male:policeman": return "male:policeman";
                case "male:enema": return "male:enema";
                case "male:low shotacon": return "male:low shotacon";
                case "male:armpit licking": return "male:armpit licking";
                case "male:butler": return "male:butler";
                case "male:apron": return "male:apron";
                case "male:bloomers": return "male:bloomers";
                case "male:diaper": return "male:diaper";
                case "male:dick growth": return "male:dick growth";
                case "male:fundoshi": return "male:fundoshi";
                case "male:bike shorts": return "male:bike shorts";
                case "male:amputee": return "male:amputee";
                case "male:giant": return "male:giant";
                case "male:lizard guy": return "male:lizard guy";
                case "male:layer cake": return "male:layer cake";
                case "male:futanari on male": return "male:futanari on male";
                case "male:full body tattoo": return "male:full body tattoo";
                case "male:stomach deformation": return "male:stomach deformation";
                case "male:gokkun": return "male:gokkun";
                case "male:ghost": return "male:ghost";
                case "male:alien": return "male:alien";
                case "male:multiple penises": return "male:multiple penises";
                case "male:fisting": return "male:fisting";
                case "male:lactation": return "male:lactation";
                case "male:nurse": return "male:nurse";
                case "male:wolf": return "male:wolf";
                case "male:corruption": return "male:corruption";
                case "male:horse boy": return "male:horse boy";
                case "male:asphyxiation": return "male:asphyxiation";
                case "male:freckles": return "male:freckles";
                case "male:insect": return "male:insect";
                case "male:selfcest": return "male:selfcest";
                case "male:waiter": return "male:waiter";
                case "male:big balls": return "male:big balls";
                case "male:ninja": return "male:ninja";
                case "male:shrinking": return "male:shrinking";
                case "male:latex": return "male:latex";
                case "male:leotard": return "male:leotard";
                case "male:vampire": return "male:vampire";
                case "male:facesitting": return "male:facesitting";
                case "male:human pet": return "male:human pet";
                case "male:deepthroat": return "male:deepthroat";
                case "male:tiara": return "male:tiara";
                case "male:metal armor": return "male:metal armor";
                case "male:slime": return "male:slime";
                case "male:big ass": return "male:big ass";
                case "male:kemonomimi": return "male:kemonomimi";
                case "male:unusual teeth": return "male:unusual teeth";
                case "male:sundress": return "male:sundress";
                case "male:pregnant": return "male:pregnant";
                case "male:gymshorts": return "male:gymshorts";
                case "male:solo action": return "male:solo action";
                case "male:shimapan": return "male:shimapan";
                case "male:long tongue": return "male:long tongue";
                case "male:christmas": return "male:christmas";
                case "male:yandere": return "male:yandere";
                case "male:whip": return "male:whip";
                case "male:chloroform": return "male:chloroform";
                case "male:cheerleader": return "male:cheerleader";
                case "male:bear boy": return "male:bear boy";
                case "male:bull": return "male:bull";
                case "male:glory hole": return "male:glory hole";
                case "male:chinese dress": return "male:chinese dress";
                case "male:body swap": return "male:body swap";
                case "male:angel": return "male:angel";
                case "male:inseki": return "male:inseki";
                case "male:breast expansion": return "male:breast expansion";
                case "male:toddlercon": return "male:toddlercon";
                case "male:bride": return "male:bride";
                case "male:monkey": return "male:monkey";
                case "male:thigh high boots": return "male:thigh high boots";
                case "male:coprophagia": return "male:coprophagia";
                case "male:priest": return "male:priest";
                case "male:infantilism": return "male:infantilism";
                case "male:autofellatio": return "male:autofellatio";
                case "male:gaping": return "male:gaping";
                case "male:cowman": return "male:cowman";
                case "male:cuntboy": return "male:cuntboy";
                case "male:impregnation": return "male:impregnation";
                case "male:bear": return "male:bear";
                case "male:schoolgirl": return "male:schoolgirl";
                case "male:double blowjob": return "male:double blowjob";
                case "male:cat": return "male:cat";
                case "male:leg lock": return "male:leg lock";
                case "male:wings": return "male:wings";
                case "male:age progression": return "male:age progression";
                case "male:uncle": return "male:uncle";
                case "male:sumata": return "male:sumata";
                case "male:breast feeding": return "male:breast feeding";
                case "male:tail plug": return "male:tail plug";
                case "male:big breasts": return "male:big breasts";
                case "male:hotpants": return "male:hotpants";
                case "male:snake": return "male:snake";
                case "male:moral degeneration": return "male:moral degeneration";
                case "male:public use": return "male:public use";
                case "male:underwater": return "male:underwater";
                case "male:large insertions": return "male:large insertions";
                case "male:magical girl": return "male:magical girl";
                case "male:corset": return "male:corset";
                case "male:miko": return "male:miko";
                case "male:gorilla": return "male:gorilla";
                case "male:necrophilia": return "male:necrophilia";
                case "male:vomit": return "male:vomit";
                case "male:cashier": return "male:cashier";
                case "male:oyakodon": return "male:oyakodon";
                case "male:skinsuit": return "male:skinsuit";
                case "male:waitress": return "male:waitress";
                case "male:eggs": return "male:eggs";
                case "male:cannibalism": return "male:cannibalism";
                case "male:frog": return "male:frog";
                case "male:parasite": return "male:parasite";
                case "male:kappa": return "male:kappa";
                case "male:body writing": return "male:body writing";
                case "male:octopus": return "male:octopus";
                case "male:stuck in wall": return "male:stuck in wall";
                case "male:shaved head": return "male:shaved head";
                case "male:midget": return "male:midget";
                case "male:dolphin": return "male:dolphin";
                case "male:gothic lolita": return "male:gothic lolita";
                case "male:wormhole": return "male:wormhole";
                case "male:tights": return "male:tights";
                case "male:oil": return "male:oil";
                case "male:reptile": return "male:reptile";
                case "male:wrestling": return "male:wrestling";
                case "male:big nipples": return "male:big nipples";
                case "male:tiger": return "male:tiger";
                case "male:body modification": return "male:body modification";
                case "male:dark sclera": return "male:dark sclera";
                case "male:centaur": return "male:centaur";
                case "male:merman": return "male:merman";
                case "male:smoking": return "male:smoking";
                case "male:wooden horse": return "male:wooden horse";
                case "male:machine": return "male:machine";
                case "male:scrotal lingerie": return "male:scrotal lingerie";
                case "male:paizuri": return "male:paizuri";
                case "male:raccoon boy": return "male:raccoon boy";
                case "male:shark boy": return "male:shark boy";
                case "male:birth": return "male:birth";
                case "male:tickling": return "male:tickling";
                case "male:mouse boy": return "male:mouse boy";
                case "male:electric shocks": return "male:electric shocks";
                case "male:balls expansion": return "male:balls expansion";
                case "male:emotionless sex": return "male:emotionless sex";
                case "male:nose hook": return "male:nose hook";
                case "male:lion": return "male:lion";
                case "male:ball sucking": return "male:ball sucking";
                case "male:nun": return "male:nun";
                case "male:pillory": return "male:pillory";
                case "male:cousin": return "male:cousin";
                case "male:shared senses": return "male:shared senses";
                case "male:sheep boy": return "male:sheep boy";
                case "male:farting": return "male:farting";
                case "male:ssbbm": return "male:ssbbm";
                case "male:blowjob face": return "male:blowjob face";
                case "male:kunoichi": return "male:kunoichi";
                case "male:low bestiality": return "male:low bestiality";
                case "male:inverted nipples": return "male:inverted nipples";
                case "male:assjob": return "male:assjob";
                case "male:swinging": return "male:swinging";
                case "male:blind": return "male:blind";
                case "male:randoseru": return "male:randoseru";
                case "male:trampling": return "male:trampling";
                case "male:forniphilia": return "male:forniphilia";
                case "male:fairy": return "male:fairy";
                case "male:grandfather": return "male:grandfather";
                case "male:absorption": return "male:absorption";
                case "male:heterochromia": return "male:heterochromia";
                case "male:unicorn": return "male:unicorn";
                case "male:slime boy": return "male:slime boy";
                case "male:anal birth": return "male:anal birth";
                case "male:rabbit": return "male:rabbit";
                case "male:speculum": return "male:speculum";
                case "male:sheep": return "male:sheep";
                case "male:growth": return "male:growth";
                case "male:petrification": return "male:petrification";
                case "male:prolapse": return "male:prolapse";
                case "male:animal on animal": return "male:animal on animal";
                case "male:slug": return "male:slug";
                case "male:phone sex": return "male:phone sex";
                case "male:horse cock": return "male:horse cock";
                case "male:gasmask": return "male:gasmask";
                case "male:hairy armpits": return "male:hairy armpits";
                case "male:all the way through": return "male:all the way through";
                case "male:pirate": return "male:pirate";
                case "male:wet clothes": return "male:wet clothes";
                case "male:pasties": return "male:pasties";
                case "male:elephant": return "male:elephant";
                case "male:multiple arms": return "male:multiple arms";
                case "male:spider": return "male:spider";
                case "male:eel": return "male:eel";
                case "male:kigurumi": return "male:kigurumi";
                case "male:milking": return "male:milking";
                case "male:goat": return "male:goat";
                case "male:fox": return "male:fox";
                case "male:body painting": return "male:body painting";
                case "male:brain fuck": return "male:brain fuck";
                case "male:donkey": return "male:donkey";
                case "male:tube": return "male:tube";
                case "male:fish": return "male:fish";
                case "male:turtle": return "male:turtle";
                case "male:pubic stubble": return "male:pubic stubble";
                case "male:weight gain": return "male:weight gain";
                case "male:shark": return "male:shark";
                case "male:penis birth": return "male:penis birth";
                case "male:crown": return "male:crown";
                case "male:clown": return "male:clown";
                case "male:saliva": return "male:saliva";
                case "male:crotch tattoo": return "male:crotch tattoo";
                case "male:armpit sex": return "male:armpit sex";
                case "male:monoeye": return "male:monoeye";
                case "male:vacbed": return "male:vacbed";
                case "male:syringe": return "male:syringe";
                case "male:zebra": return "male:zebra";
                case "male:big areolae": return "male:big areolae";
                case "male:witch": return "male:witch";
                case "male:dinosaur": return "male:dinosaur";
                case "male:nazi": return "male:nazi";
                case "male:balljob": return "male:balljob";
                case "male:twintails": return "male:twintails";
                case "male:harpy": return "male:harpy";
                case "male:insect boy": return "male:insect boy";
                case "male:mecha boy": return "male:mecha boy";
                case "male:worm": return "male:worm";
                case "male:panther": return "male:panther";
                case "male:ponytail": return "male:ponytail";
                case "male:bodystocking": return "male:bodystocking";
                case "male:living clothes": return "male:living clothes";
                case "male:triple penetration": return "male:triple penetration";
                case "male:plant boy": return "male:plant boy";
                case "male:pegasus": return "male:pegasus";
                case "male:squid boy": return "male:squid boy";
                case "male:dark nipples": return "male:dark nipples";
                case "male:hairjob": return "male:hairjob";
                case "male:beauty mark": return "male:beauty mark";
                case "male:muscle growth": return "male:muscle growth";
                case "male:gijinka": return "male:gijinka";
                case "male:triple anal": return "male:triple anal";
                case "male:mouse": return "male:mouse";
                case "male:ostrich": return "male:ostrich";
                case "male:stewardess": return "male:stewardess";
                case "male:tooth brushing": return "male:tooth brushing";
                case "male:adventitious penis": return "male:adventitious penis";
                case "male:whale": return "male:whale";
                case "male:doll joints": return "male:doll joints";
                case "male:snake boy": return "male:snake boy";
                case "male:dismantling": return "male:dismantling";
                case "male:clamp": return "male:clamp";
                case "male:animal on furry": return "male:animal on furry";
                case "male:navel fuck": return "male:navel fuck";
                case "male:steward": return "male:steward";
                case "male:nipple fuck": return "male:nipple fuck";
                case "male:cum bath": return "male:cum bath";
                case "male:tailjob": return "male:tailjob";
                case "male:stretching": return "male:stretching";
                case "male:rhinoceros": return "male:rhinoceros";
                case "male:foot insertion": return "male:foot insertion";
                case "male:alligator": return "male:alligator";
                case "male:maggot": return "male:maggot";
                case "male:closed eyes": return "male:closed eyes";
                case "male:bunny girl": return "male:bunny girl";
                case "male:lizard": return "male:lizard";
                case "male:squirrel boy": return "male:squirrel boy";
                case "male:crab": return "male:crab";
                case "male:pantyjob": return "male:pantyjob";
                case "male:table masturbation": return "male:table masturbation";
                case "male:pole dancing": return "male:pole dancing";
                case "male:glothic loli": return "male:glothic loli";
                case "male:tall guy": return "male:tall guy";
                case "male:plant guy": return "male:plant guy";
                case "male:tentecale": return "male:tentecale";
                case "male:eye penetration": return "male:eye penetration";
                case "male:golbin": return "male:golbin";
                case "male:camel": return "male:camel";
                case "male:harness": return "male:harness";
                case "male:anorexic": return "male:anorexic";
                case "male:dicknipples": return "male:dicknipples";

            }

            return eng_tag;
        }
    }
}
